language: cpp
compiler: g++
before_install:
  - sudo apt-get install libboost-dev
  - dpkg -L libboost-dev
  - ls -la /usr/local
  - ls -la /usr/local/lib
  - ls -la /usr/local/include
  - ls -la /usr/lib
  - ls -la /usr/include
  - locate libboost_system.so
script: make test
